### About the Notebook

This notebook is a reproduction of the Notebook by Francois Chollet explaining what needs to be known to researchers to be able to use Tensorflow 2.0 for reproducing Papers. We will build a Linear Layer but have a separate for building the weights. This will remove the need to specify the input_shape in the __init__ method.

We will start with importing the Layer Class first. As is the norm let us import tensorflow and check the version. We will also import keras.

In [1]:
import tensorflow as tf
print(tf.__version__)

2.0.0-alpha0


In [2]:
from tensorflow import keras
from tensorflow.keras.layers import Layer

### Linear Layer

In [3]:
class Linear(Layer):
    def __init__(self,units=32):
        super(Linear,self).__init__()
        self.units=units
    ### The build method is to build the weights
    def build(self,input_shape):
        ### We will build the weight using self.add_weight using shape, initializer and setting trainable 
        ### to be true
        self.w = self.add_weight(shape=(input_shape[-1],self.units),initializer='random_normal',trainable=True)
        self.b = self.add_weight(shape=(self.units,),initializer='random_normal',trainable=True)
    
    ### The call method is use to do the computation required in the Layer
    def call(self,inputs):
        return tf.matmul(inputs,self.w)+self.b

### Test the Linear Layer

In [4]:
### Create a test_layer which is an instance of the Linear Layer
test_layer = Linear(4)

Since the model is to build the weights when the output is called, we will not be able to see the variables and weights

In [5]:
test_layer.variables

[]

In [6]:
test_layer.weights

[]

### Build the Model
Let's call the model with an input so that we can generate the output, once this is done we can see the variables and the weights as well

In [7]:
### Lets Provide an input which is tf.ones((2,2))
### The output of this input through this test_layer can be found as follows
y = test_layer(tf.ones((2,2)))
print("The Value of y is :")
print(y)
print("The shape of y is: ")
print(y.shape)

The Value of y is :
tf.Tensor(
[[ 0.08546811  0.02743595  0.00682419 -0.10033746]
 [ 0.08546811  0.02743595  0.00682419 -0.10033746]], shape=(2, 4), dtype=float32)
The shape of y is: 
(2, 4)


### Variables

In [8]:
### Get the Variables associated with the test layer
Weight,Bias = test_layer.variables
print('The variables in this layer are the Weight Variable: {}'.format(Weight))
print('\n''and the Bias Variable: {}'.format(Bias))


The variables in this layer are the Weight Variable: <tf.Variable 'linear/Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[-0.02470994, -0.04151258,  0.03872228,  0.00811936],
       [ 0.07231567,  0.06020617, -0.01718306,  0.01237033]],
      dtype=float32)>

and the Bias Variable: <tf.Variable 'linear/Variable:0' shape=(4,) dtype=float32, numpy=array([ 0.03786239,  0.00874236, -0.01471503, -0.12082715], dtype=float32)>


### Weights

In [9]:
### We can also only get the weights and bias if we so desire
### Find the weights and Bias of the Layer
weights,bias = test_layer.weights
### Print the Weights of the Layer
print("The weights of this layer are :")
print(weights)
### Print the Bias of the Layer
print("The bias of this layer are :")
print(bias)

The weights of this layer are :
<tf.Variable 'linear/Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[-0.02470994, -0.04151258,  0.03872228,  0.00811936],
       [ 0.07231567,  0.06020617, -0.01718306,  0.01237033]],
      dtype=float32)>
The bias of this layer are :
<tf.Variable 'linear/Variable:0' shape=(4,) dtype=float32, numpy=array([ 0.03786239,  0.00874236, -0.01471503, -0.12082715], dtype=float32)>
