### About the Notebook

This notebook is a reproduction of the Notebook by Francois Chollet explaining what needs to be known to researchers to be able to use Tensorflow 2.0 for reproducing Papers

We will start with importing the Layer Class first. As is the norm let us import tensorflow and check the version

In [1]:
import tensorflow as tf
print(tf.__version__)

2.0.0-alpha0


In [2]:
from tensorflow import keras
from tensorflow.keras.layers import Layer

### Linear Layer

In [3]:
class Linear(Layer):
    def __init__(self,units=32,input_shape=32):
        super(Linear,self).__init__()
        ### we will initialise the weights and the bias
        ### Weights will be random_normal initialised
        ### Bias will be zero initialised
        w_init = tf.random_normal_initializer()
        b_init = tf.zeros_initializer()
        ### we will create the weights and bias for the Layer and set them to be trainable
        self.w = tf.Variable(initial_value=w_init(shape=(input_shape,units),dtype='float32'),trainable=True)
        ### We will do the same for the bias as well
        self.b = tf.Variable(initial_value=b_init(shape=(units,),dtype='float32'),trainable=True)
    
    ### The call method is use to do the computation required in the Layer
    def call(self,inputs):
        return tf.matmul(inputs,self.w)+self.b

### Test the Linear Layer

In [4]:
### Create a test_layer which is an instance of the Linear Layer
test_layer = Linear(4,2)

In [5]:
### Get the Variables associated with the test layer
Weight,Bias = test_layer.variables
print('The variables in this layer are the Weight Variable: {}'.format(Weight))
print('\n''and the Bias Variable: {}'.format(Bias))


The variables in this layer are the Weight Variable: <tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[-0.02464332, -0.03039652, -0.05483612, -0.00165784],
       [-0.03904807, -0.05201383, -0.00533114,  0.02012433]],
      dtype=float32)>

and the Bias Variable: <tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>


In [6]:
### We can also only get the weights and bias if we so desire
### Find the weights and Bias of the Layer
weights,bias = test_layer.weights
### Print the Weights of the Layer
print("The weights of this layer are :")
print(weights)
### Print the Bias of the Layer
print("The bias of this layer are :")
print(bias)

The weights of this layer are :
<tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[-0.02464332, -0.03039652, -0.05483612, -0.00165784],
       [-0.03904807, -0.05201383, -0.00533114,  0.02012433]],
      dtype=float32)>
The bias of this layer are :
<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>


In [7]:
### Lets Provide an input which is tf.ones((2,2))
### The output of this input through this test_layer can be found as follows
y = test_layer(tf.ones((2,2)))
print("The Value of y is :")
print(y)
print("The shape of y is: ")
print(y.shape)

The Value of y is :
tf.Tensor(
[[-0.06369139 -0.08241034 -0.06016726  0.01846649]
 [-0.06369139 -0.08241034 -0.06016726  0.01846649]], shape=(2, 4), dtype=float32)
The shape of y is: 
(2, 4)
